#!/usr/bin/env bash

rm -rf /tmp/cljdoc
mkdir -p /tmp/cljdoc
version=$(cat resources/CLJ_JQ_VERSION)

echo "---- cljdoc preview: installing jar in local repo"
mvn install

echo "---- cljdoc preview: ingesting clj-jq"
docker run --rm -v "$PWD:/clj-jq" \
       -v "$HOME/.m2:/root/.m2" -v /tmp/cljdoc:/app/data --entrypoint "clojure" \
       cljdoc/cljdoc -A:cli ingest -p lt.jocas/clj-jq -v "$version" \
       --git /clj-jq

echo "---- cljdoc preview: starting server on port 8000"
docker run --rm -p 8000:8000 -v /tmp/cljdoc:/app/data cljdoc/cljdoc
# go directly to http://localhost:8000/d/lt.jocas/clj-jq/, not via the search
