#!/usr/bin/env bash
: "${lib:=clj-jq}"

export JAVA_HOME=${GRAALVM_HOME?Please set GRAALVM_HOME}
export PATH=$GRAALVM_HOME/bin:$PATH

"$GRAALVM_HOME/bin/gu" install native-image || true

CLJ_JQ_VERSION=$(<resources/CLJ_JQ_VERSION)

args=( "-jar" "target/$lib-$CLJ_JQ_VERSION-standalone.jar"
       "-H:Name=$lib"
       "-H:+ReportExceptionStackTraces"
       "--initialize-at-build-time"
       "-H:Log=registerResource:"
       "--verbose"
       "--no-fallback"
       "-J-Xmx8g" )

if [ "$CLJ_JQ_STATIC" = "true" ]; then
    args+=("--static")
    if [ "$CLJ_JQ_MUSL" = "true" ]; then
        args+=("--libc=musl")
    fi
fi

exec "$GRAALVM_HOME/bin/native-image" "${args[@]}" "$@"
