name: clj-kondo linting

on:
  push:
    branches:
      - '**'
      - '!v*'
    tags:
      - '!v*'
    paths-ignore:
      - 'pom.xml'

jobs:
  lint-code:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0
      - name: Install clojure, bb, clj-kondo
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: '1.11.1.1413'
          bb: '1.3.181'
          clj-kondo: '2023.09.07'

      - name: Lint the code
        run: clj-kondo --lint src test
