name: clj-kondo linting

on:
  push:
    branches:
      - '**'
      - '!v*'
    tags:
      - '!v*'
    paths-ignore:
      - 'pom.xml'

jobs:
  lint-code:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3
      - uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint src test
          # secrets.GITHUB_TOKEN is needed here
          # to publish annotations back to github
          # this action is not storing or sending it anywhere
          github_token: ${{ secrets.GITHUB_TOKEN }}
