name: Tests

on:
  push:
    branches:
      - '**'
      - '!clj-jq-*'
    tags:
      - '!clj-jq-*'
    paths-ignore:
      - 'pom.xml'

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache maven deps
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare java
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 8.0.292+10
          distribution: 'adopt'

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: 1.10.3.956

      - name: Unit Tests
        run: |
          clojure -A:dev:test
          git branch –show-current
