name: Tests

on:
  push:
    branches:
      - '**'
      - '!v*'
    tags:
      - '!v*'
    paths-ignore:
      - 'pom.xml'

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0

      - name: Cache maven deps
        uses: actions/cache@v3.3.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare java
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: 1.11.1.1413

      - name: Unit Tests
        run: clojure -A:dev:test
