name: Tests

on:
  push:
    branches:
      - '**'
      - '!v*'
    tags:
      - '!v*'
    paths-ignore:
      - 'pom.xml'

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Cache maven deps
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare java
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: 1.11.1.1273

      - name: Unit Tests
        run: clojure -A:dev:test
