name: TEST JOB

on: [push]

jobs:

  compile-windows-native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        include:
          - os: windows-latest
            platform: windows
            arch: 'amd64'
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'

      - name: Set env
        run: |
          echo ("RELEASE_VERSION=" + $env:GITHUB_REF.replace('refs/heads/', '')) >> $env:GITHUB_ENV

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: 1.10.3.956
          cli: 1.10.3.956

      - name: Compile uberjar on windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          clojure -T:build uber
        shell: powershell

      - uses: ilammy/msvc-dev-cmd@v1.5.0
      - uses: microsoft/setup-msbuild@v1
      - name: Set env
        shell: powershell
        run: |
          echo ("CLJ_JQ_VERSION=" + $(cat resources/CLJ_JQ_VERSION)) >> $env:GITHUB_ENV

      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.2.0
          native-image: true

      - name: Build native image
        run: |
          native-image -jar "target/clj-jq-$env:CLJ_JQ_VERSION-standalone.jar" -H:Name=clj-jq -H:+ReportExceptionStackTraces --initialize-at-build-time --verbose --no-fallback -J-Xmx8g
        shell: powershell

      - name: Zip executable
        shell: powershell
        run: |
          tar.exe -a -c -f clj-jq-${{ env.RELEASE_VERSION }}-${{ matrix.platform }}-${{ matrix.arch }}.zip clj-jq.exe
          ls .
          ./clj-jq.exe -h
